package spam;

import java.util.ArrayList;
import java.util.List;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import server.Server;

/**
 *
 * @author Seba
 */
public class SpamPanel extends javax.swing.JPanel
{
	Server parent;

	/**
	 * Creates new form SpamPanel
	 */
	public SpamPanel()
	{
		initComponents();
	}
	public SpamPanel(Server parent) {
		this.parent = parent;
		initComponents();
		
		//Sortowanie
		TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(ignoredTable.getModel());
		ignoredTable.setRowSorter(sorter);
		List<RowSorter.SortKey> sortKeys = new ArrayList<>(25);
		sortKeys.add(new RowSorter.SortKey(2, SortOrder.DESCENDING));
		sorter.setSortKeys(sortKeys);
		sorter.setSortsOnUpdates(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jLabel1 = new javax.swing.JLabel();
    selectedUserName = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    ignoredTable = new javax.swing.JTable();
    disconnect = new javax.swing.JButton();

    jLabel1.setText("Wybrany użytkownik:");

    ignoredTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {

      },
      new String []
      {
        "Użytkownik", "IP", "Ignorowany"
      }
    )
    {
      Class[] types = new Class []
      {
        java.lang.String.class, java.lang.String.class, java.lang.Integer.class
      };
      boolean[] canEdit = new boolean []
      {
        false, false, false
      };

      public Class getColumnClass(int columnIndex)
      {
        return types [columnIndex];
      }

      public boolean isCellEditable(int rowIndex, int columnIndex)
      {
        return canEdit [columnIndex];
      }
    });
    ignoredTable.setColumnSelectionAllowed(true);
    ignoredTable.getTableHeader().setReorderingAllowed(false);
    ignoredTable.addMouseListener(new java.awt.event.MouseAdapter()
    {
      public void mouseClicked(java.awt.event.MouseEvent evt)
      {
        ignoredTableMouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(ignoredTable);
    ignoredTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

    disconnect.setText("Rozłącz");
    disconnect.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        disconnectActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(11, 11, 11)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(selectedUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(disconnect)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(selectedUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(disconnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void disconnectActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_disconnectActionPerformed
  {//GEN-HEADEREND:event_disconnectActionPerformed
    // TODO add your handling code here:
		parent.RemoveSelected();
  }//GEN-LAST:event_disconnectActionPerformed

  private void ignoredTableMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_ignoredTableMouseClicked
  {//GEN-HEADEREND:event_ignoredTableMouseClicked
    // TODO add your handling code here:
		int selectedRow = ignoredTable.getSelectedRow();
		String userName = ignoredTable.getValueAt(selectedRow, 0).toString();
		selectedUserName.setText(userName);
  }//GEN-LAST:event_ignoredTableMouseClicked


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton disconnect;
  public javax.swing.JTable ignoredTable;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JLabel selectedUserName;
  // End of variables declaration//GEN-END:variables
}
